spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple_spring
    username: spring_user
    password: spring_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true